# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'mechanize'
gem 'oauth2', '~> 1.2'
gem 'dotenv-rails', groups: [:development, :test]

